### ISSUE TITLE
Plans to publish?

### ISSUE THREAD

**Issue by benwiley4000** [hunter-packages/freeimage#1]
I've been looking for an image decoding library readily available through Hunter - is this in a publishable state?

**Comment by ruslo** [comment]
This fork was created for this issue:
* https://github.com/ruslo/hunter/issues/363

Instructions for adding new package is here:
* https://docs.hunter.sh/en/latest/creating-new.html

Feel free to work on it.

**Comment by ruslo** [comment]
Closing inactive discussion.
